version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          BUNDLER_VERSION: 2.0.2
    working_directory: ~/work_furukawa_first_gem
commands:
  setup-bundler:
    description: "setup bundler 2"
    steps:
      - run: sudo gem update --system
      - run: sudo gem uninstall bundler
      - run: sudo rm /usr/local/bin/bundle
      - run: sudo rm /usr/local/bin/bundler
      - run: sudo gem install bundler
jobs:
  my-job:
    executor: my-executor
    steps:
      - checkout
      - setup-bundler
      - run: bundle update rake
      - run: bundle exec rake spec
workflows:
  my-workflow:
    jobs:
      - my-job
