version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          BUNDLER_VERSION: 2.0.2
    working_directory: ~/work_furukawa_first_gem
    steps:
      - checkout
      - run: bundle exec rake spec
